version: '3.1'

networks:
  maticar:
    name: maticar


services:
  maticar:
    build:
      context: ./maticar-backend/
      args:
        - APP_VERSION
    container_name: maticar
    volumes:
      - ./maticar-backend/htmlcov:/opt/app/htmlcov
    environment:
      - DEVELOP
      - APP_VERSION
      - LOG_LEVEL
      - SECRET
      - ALGORITHM
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB
      - MYSQL_HOST
      - MYSQL_PORT
      - REDIS_HOST
    networks:
      maticar:
        aliases:
          - app
    ports:
      - "8080:80"
    depends_on:
      mysqlDB:
        condition: service_healthy
      redisDB:
        condition: service_healthy

  mysqlDB:
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysqlDB:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      maticar:
        aliases:
        - ${MYSQL_HOST}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  redisDB:
    image: redis:6.2.0
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redisDB:/data
    ports:
      - "6379:6379"
    networks:
      maticar:
        aliases:
        - ${REDIS_HOST}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  mysqlDB:
    driver: local
  redisDB:
    driver: local
